# Generated by Django 5.0.2 on 2024-11-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('HoleID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Ownership', models.CharField(max_length=255)),
                ('Project', models.CharField(max_length=255)),
                ('Prospect', models.CharField(blank=True, max_length=255, null=True)),
                ('Projection', models.CharField(blank=True, max_length=50, null=True)),
                ('Easting', models.FloatField(blank=True, null=True)),
                ('Northing', models.FloatField(blank=True, null=True)),
                ('SurveyMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('RL', models.FloatField(blank=True, null=True)),
                ('PlottingRL', models.FloatField(blank=True, null=True)),
                ('Dip', models.FloatField(blank=True, null=True)),
                ('TotalDepth', models.FloatField(blank=True, null=True)),
                ('LoggedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('TenementName', models.CharField(blank=True, max_length=255, null=True)),
                ('TenementNo', models.CharField(blank=True, max_length=50, null=True)),
                ('WaterDepth', models.FloatField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DHDrillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepthFrom', models.FloatField()),
                ('DepthTo', models.FloatField()),
                ('DrillType', models.CharField(blank=True, max_length=50, null=True)),
                ('HoleSize', models.FloatField(blank=True, null=True)),
                ('DrillRig', models.CharField(blank=True, max_length=255, null=True)),
                ('DateStarted', models.DateField(blank=True, null=True)),
                ('DateCompleted', models.DateField(blank=True, null=True)),
                ('HoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.collar')),
            ],
        ),
        migrations.CreateModel(
            name='DHGeology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepthFrom', models.FloatField()),
                ('DepthTo', models.FloatField()),
                ('Regolith', models.CharField(blank=True, max_length=50, null=True)),
                ('Lithology1', models.CharField(blank=True, max_length=255, null=True)),
                ('Lith1_pct', models.FloatField(blank=True, null=True)),
                ('Lithology2', models.CharField(blank=True, max_length=255, null=True)),
                ('Lith2_pct', models.FloatField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('HoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.collar')),
            ],
        ),
        migrations.CreateModel(
            name='DHMagSus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepthFrom', models.FloatField()),
                ('DepthTo', models.FloatField()),
                ('MagSus1', models.FloatField(blank=True, null=True)),
                ('MagSus2', models.FloatField(blank=True, null=True)),
                ('MagSus3', models.FloatField(blank=True, null=True)),
                ('MagSusAverage', models.FloatField(blank=True, null=True)),
                ('HoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.collar')),
            ],
        ),
        migrations.CreateModel(
            name='DHSample',
            fields=[
                ('SampleID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('DepthFrom', models.FloatField()),
                ('DepthTo', models.FloatField()),
                ('Interval', models.FloatField(blank=True, null=True)),
                ('SampType', models.CharField(blank=True, max_length=50, null=True)),
                ('SampleSubType', models.CharField(blank=True, max_length=50, null=True)),
                ('HoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.collar')),
            ],
        ),
        migrations.CreateModel(
            name='DHAssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepthFrom', models.FloatField()),
                ('DepthTo', models.FloatField()),
                ('Au_ppm', models.FloatField(blank=True, null=True)),
                ('Ag_ppm', models.FloatField(blank=True, null=True)),
                ('Fe_pct', models.FloatField(blank=True, null=True)),
                ('HoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.collar')),
                ('SampleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.dhsample')),
            ],
        ),
        migrations.CreateModel(
            name='DHScint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepthFrom', models.FloatField()),
                ('DepthTo', models.FloatField()),
                ('Average_cps', models.FloatField(blank=True, null=True)),
                ('CB_eTh', models.FloatField(blank=True, null=True)),
                ('CB_eU', models.FloatField(blank=True, null=True)),
                ('CB_K', models.FloatField(blank=True, null=True)),
                ('Scintillometer', models.CharField(blank=True, max_length=255, null=True)),
                ('HoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.collar')),
            ],
        ),
        migrations.CreateModel(
            name='DHSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Depth', models.FloatField()),
                ('Dip', models.FloatField(blank=True, null=True)),
                ('AzimMag', models.FloatField(blank=True, null=True)),
                ('AzimUTM', models.FloatField(blank=True, null=True)),
                ('DateSurveyed', models.DateField(blank=True, null=True)),
                ('SurveyedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('HoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.collar')),
            ],
        ),
    ]
