name: 'Notification des dates d\'échéance'
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Envoi de notifications pour les échéances
        uses: petrandr/duedate_reminders@latest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          smtp_server: "smtp.isms.esp.mr"
          smtp_port: 587
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          smtp_from_email: "20226@isms.esp.mr"
          to_emails: "23015@esp.mr, 23014@esp.mr"
