name: 'Rappel des tâches quotidiennes'

on:
  schedule:
    - cron: '0 8 * * *' # Exécution quotidienne à 8h00 UTC

jobs:
  send-task-reminders:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer les tâches assignées dans le projet
      - name: Récupérer les tâches du projet
        id: get-tasks
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Récupérer toutes les issues ouvertes
            const issues = await github.issues.listForRepo({
              owner,
              repo,
              state: "open"
            });

            // Filtrer les issues assignées
            const assignedTasks = issues.data
              .filter(issue => issue.assignees.length > 0)
              .map(issue => ({
                assignee: issue.assignees.map(a => a.login).join(", "), // Logins des assignés
                title: issue.title,
                url: issue.html_url
              }));

            // Formater les tâches pour l'envoi par e-mail
            const tasksPerAssignee = {};
            assignedTasks.forEach(task => {
              const assignees = task.assignee.split(", ");
              assignees.forEach(assignee => {
                if (!tasksPerAssignee[assignee]) {
                  tasksPerAssignee[assignee] = [];
                }
                tasksPerAssignee[assignee].push(`- ${task.title} (${task.url})`);
              });
            });

            // Générer la sortie pour l'étape suivante
            core.setOutput("tasks", JSON.stringify(tasksPerAssignee));

      # Étape 2 : Envoyer des e-mails
      - name: Envoyer les rappels par e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.isms.esp.mr
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Rappel des tâches du projet GitHub"
          body: |
            Bonjour,

            Voici vos tâches assignées dans le projet GitHub :

            {{ tasks_list }}

            Bonne journée !
          to: ${{ secrets.RECIPIENT_EMAILS }}
          from: ${{ secrets.SMTP_USERNAME }}
        env:
          TASKS_LIST: ${{ steps.get-tasks.outputs.tasks }}
